spring.application.name=vehicle-service

# Service Port
server.port=1111

# MySQL Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Dhaya@123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Configuration
# Kafka Broker (Default local port)
spring.kafka.bootstrap-servers=localhost:9092

# Producer Settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer Settings
spring.kafka.consumer.group-id=vehicle-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
